baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "en"
# 网站语言, 仅在这里 CN 大写
languageCode = "en"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Welcome to my blogs"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
  # DoIt 主题版本
  version = "0.2.X"
  images = ["/images/avatar.png"]
  [params.home]
    # 主页信息设置
    [params.home.profile]
      # Gravatar 邮箱, 用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"
      subtitle = "Welcome to my page"
      social = true
    [params.home.posts]
      # 是否在主页显示文章摘要
      enable = false
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "DoIt"
    # whether to omit favicon resource links
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Android browser theme color
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari mask icon color
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-11 tile color
    # Windows v8-11 磁贴颜色
    tileColor = "#da532c"
  
  [params.social]
    GitHub = "xxxx"
    Linkedin = ""
    Twitter = "xxxx"
    Instagram = "xxxx"
    Facebook = "xxxx"
    Telegram = "xxxx"
    [params.social.Mastodon]
      # 排列图标时的权重 (权重越大, 图标的位置越靠后)
      weight = 0
      # 你的社交 ID
      id = "@xxxx"
      # 你的社交链接的前缀
      prefix = "https://mastodon.social/"
      # 当鼠标停留在图标上时的提示内容
      title = "Mastodon"
  [params.page]
	[params.page.seo]
      # image URL
      # 图片 URL
      images = []
      # Publisher info
      # 出版者信息
      [params.page.seo.publisher]
        name = "xxxx"
        logoUrl = "/images/avatar.png"
  [params.seo]
    # image URL
    # 图片 URL
    image = "/images/avatar.png"
    # thumbnail URL
    # 缩略图 URL
    thumbnailUrl = "/images/avatar.png"
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    # 页面头部导航栏标题配置
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      logo = ""
      # title name
      # 标题名称
      name = "DoIt"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = false
	


  
  
 
	
[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "blogs"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
#  [[menu.main]]
#    identifier = "categories"
#    pre = ""
#    post = ""
#    name = "categories"
#    url = "/categories/"
#    title = ""
#    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "about"
    url = "/about/"
    title = ""
    weight = 3
	
  [[menu.main]]
    identifier = "friend link"
    pre = ""
    post = ""
    name = "friend link"
    url = "/friend link/"
    title = ""
    weight = 4
  
	
	
	
	
# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
